version: '3.8'

services:
  # Frontend React Application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: waste-management-client
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - waste-management-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  waste-management-network:
    driver: bridge